name: Tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn test --ci
